# Generated by Django 5.0.6 on 2024-09-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterModel',
            new_name='WardenRegisterModel',
        ),
    ]
