# Generated by Django 5.0.6 on 2024-08-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('regNo', models.IntegerField(unique=True)),
                ('dept_year', models.IntegerField()),
                ('pic', models.CharField(max_length=200, verbose_name='student_profile_pic')),
                ('district', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
