# Generated by Django 5.0.6 on 2024-08-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='dept_year',
        ),
        migrations.AddField(
            model_name='registermodel',
            name='dept',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
