# Generated by Django 5.0.6 on 2024-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_registermodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='pending',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], null=True),
        ),
    ]
