# Generated by Django 5.0.6 on 2024-08-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_registermodel_dept_year_registermodel_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='dept',
            field=models.CharField(default='', max_length=150),
        ),
    ]
