# Generated by Django 5.0.6 on 2024-08-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_registermodel_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
