# Generated by Django 5.0.6 on 2024-09-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_requestmodel_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Final Year')], help_text='1-first_year, 2-second_year, 3-third_year, 4-final_year', null=True),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='pending',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1, help_text='1-pending, 2-accepted, 3-rejected', null=True),
        ),
    ]
