# Generated by Django 5.0.6 on 2024-08-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_registermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='pic',
            field=models.ImageField(max_length=200, upload_to='', verbose_name='student_profile_pic'),
        ),
    ]
