# Generated by Django 4.1 on 2024-09-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_registermodel_year_alter_requestmodel_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[], help_text='1-first_year, 2-second_year, 3-third_year, 4-final_year', null=True),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='pending',
            field=models.PositiveSmallIntegerField(choices=[], default=1, help_text='1-pending, 2-accepted, 3-rejected', null=True),
        ),
    ]
