# Generated by Django 5.0.6 on 2024-09-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_registermodel_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='dept',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='district',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='phone_number',
            new_name='Phone_number',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='regNo',
            new_name='RegisterNumber',
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='pic',
        ),
    ]
