# Generated by Django 5.1 on 2024-09-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_registermodel_year_alter_requestmodel_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='gateInTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='gateOutTime',
            field=models.DateTimeField(null=True),
        ),
    ]
