# Generated by Django 5.0.6 on 2024-09-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_dept_registermodel_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='RegisterNumber',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
