# Generated by Django 5.1 on 2024-09-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_requestmodel_gateintime_requestmodel_gateouttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='outpassEnd',
            field=models.BooleanField(default=0),
        ),
    ]
