# Generated by Django 5.1 on 2024-09-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_requestmodel_outpassend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='gateInTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='gateOutTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
