# Generated by Django 5.0.6 on 2024-09-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_registermodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='Phone_number',
            field=models.BigIntegerField(),
        ),
    ]
