# Generated by Django 5.0.6 on 2024-09-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_registermodel_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='District',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='RegisterNumber',
            new_name='register_number',
        ),
    ]
