# Generated by Django 5.1 on 2024-09-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_requestmodel_gateintime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='actionWarden',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
