# Generated by Django 4.1 on 2024-09-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_requestmodel_actionwarden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='pending',
            field=models.CharField(choices=[], default=1, help_text='1-pending, 2-accepted, 3-rejected', max_length=100, null=True),
        ),
    ]
