# Generated by Django 4.1 on 2024-09-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_requestmodel_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='pending',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1, help_text='1-pending, 2-accepted, 3-rejected', max_length=100, null=True),
        ),
    ]
