# Generated by Django 4.1 on 2024-09-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_requestmodel_roomno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='roomNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
