# Generated by Django 4.1 on 2024-09-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_requestmodel_roomno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='register_number',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
