# Generated by Django 4.1 on 2024-09-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_registermodel_register_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='year',
            field=models.IntegerField(choices=[], help_text='1-first_year, 2-second_year, 3-third_year, 4-final_year', null=True),
        ),
    ]
