# Generated by Django 4.1 on 2024-09-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_registermodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='year',
            field=models.CharField(choices=[(1, 'First Year'), (2, 'Second year'), (3, 'Third year'), (4, 'Final year')], help_text='1-first_year, 2-second_year, 3-third_year, 4-final_year', max_length=150, null=True),
        ),
    ]
