# Generated by Django 5.1 on 2024-09-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylogin',
            name='phone_number',
            field=models.BigIntegerField(null=True, verbose_name='security_phone_number'),
        ),
    ]
