# Generated by Django 5.1 on 2024-09-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_securitylogin_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylogin',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='security_phone_number'),
        ),
    ]
