# Generated by Django 4.1 on 2024-09-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_securitylogin_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='securityLogin',
            new_name='securityLoginModel',
        ),
    ]
